spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      username: root
      password: ibXCziJp6ExmmJPd
      url: jdbc:p6spy:mysql://124.222.190.65:3306/submarine?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=false&nullCatalogMeansCurrent=true
      driverClassName: com.p6spy.engine.spy.P6SpyDriver
      validationQuery: SELECT 1
      testWhileIdle: true
      stat-view-servlet:
        # 默认true 内置监控页面首页 http://localhost:19687/api/druid/login.html
        enabled: true
        url-pattern: /druid/*
        # 允许清空统计数据
        reset-enable: true
        login-username: root
        login-password: 123456
      filters: stat
  # 开发环境session持久化，方便开发，生产环境自行决定是否持久化
  session:
    store-type: redis
    timeout: 10H
    redis:
      flush-mode: on_save
      namespace: springboot-session

  redis:
    database: 5
    host: 127.0.0.1
    port: 6379
    password:
    lettuce:
      pool:
        max-active: 8
dev:
  validator:
    enable: true

ele:
  info:
    appkey: 26843883
    secKey: JW53DmDe1W



upload:
  type: local
  local:
    path: ./src/main/resources/public/

pay:
  doMainUrl: http://api2.lfwin.com
  apikey: 18742301
  signkey: 38874674
